apiVersion: v1
kind: Service
metadata:
  name: result
  labels:
    app: result

spec:
  type: NodePort
  ports:
    -  name: "result-service"
       nodePort: 31000
       port: 80
       targetPort: 80
  selector:
    app: result
      
