apiVersion: v1
kind: Service
metadata:
  name: db
  labels:
    app: db

spec:
# using ClusterIP 
  ports:
    -  name: "db-service"
       port: 5432
       targetPort: 5432
  selector:
    app: db
      
