apiVersion: v1
kind: Service
metadata:
  name: vote
  labels:
    app: vote

spec:
  type: NodePort
  ports:
    -  name: "vote-service"
       nodePort: 30008
       port: 80
       targetPort: 80
  selector:
    app: vote
      
